### PR TITLE
Add support to clang-format 8 and 9

### PR DESCRIPTION
**Pull request by tristan0x**
Current issue is that despite my efforts to tweaks the configuration,
the formatting is slightly different between the 2 versions,
at least for project zee.

### CODE REVIEW

**Comment by matz-e** [comment]
I plan on deploying LLVM 9 on the cluster, too. Would be nice to maybe support 7 & 9?

**Comment by tristan0x** [comment]
> I plan on deploying LLVM 9 on the cluster, too. Would be nice to maybe support 7 & 9?

There are contributors outside BBP that will need to format their contribution. So ideally, I would like to support 7, 8, and 9.

**Comment by matz-e** [comment]
> > I plan on deploying LLVM 9 on the cluster, too. Would be nice to maybe support 7 & 9?
> 
> There are contributors outside BBP that will need to format their contribution. So ideally, I would like to support 7, 8, and 9.

OK. Just a heads up that 9 will be available, too. We may want to switch our internal recommendation to 9 if it proves reliable.

**Comment by tristan0x** [comment]
> > > I plan on deploying LLVM 9 on the cluster, too. Would be nice to maybe support 7 & 9?
> > 
> > 
> > There are contributors outside BBP that will need to format their contribution. So ideally, I would like to support 7, 8, and 9.
> 
> OK. Just a heads up that 9 will be available, too. We may want to switch our internal recommendation to 9 if it proves reliable.

Yes. Version 9 will be the one recommended by this coding convention.

**Pull request merged**
