### PR TITLE
now requires CMake 3.10 or higher (the one shipped with Ubuntu bionic LTS)

### PR DESCRIPTION
**Pull request by tristan0x**

### CODE REVIEW

**Review by matz-e — COMMENTED** [review]
No other review?

**Comment by tristan0x** [comment]
> No other review?

Not enforced on this repository.

**Comment by matz-e** [comment]
Why not?

**Comment by pramodk** [comment]
As we have now more traction here and more and more projects depend on it, good idea to enable reviews now.

**Pull request merged**
