### PR TITLE
Create license.txt

### PR DESCRIPTION
**Pull request by ASVG**
Assuming that there is no dependency license conflicts, I would like to propose a license.txt.
To be absolutely certain, please run https://bbpteam.epfl.ch/project/spaces/display/QA/OSS+License+check+tool

Thank you.

### CODE REVIEW

**Comment by pramodk** [comment]
@tristan0x : you might have better view of different components used here. Could you take a look?

**Comment by pramodk** [comment]
I see that there is related PR #99 as well.

**Comment by tristan0x** [comment]
Thank you @ASVG 
Apache Licence doesn't allow _copyleft_, I would rather use the LGPL3 licence if you don't mind.

**Comment by ASVG** [comment]
Hello Tristan

That is exactly the point! strong copyleft has restrictions that are often difficult to maintain. BBP as a whole, now recommends Apache unless there is a good reason not to (e.g., has strong copyleft dependency). Did you find dependency with GPL or BSL? FYI, LGPL requires that you put LGPL License and copyright indication (copyright (c) 2022 BBP/EPFL) on "all files".

**Comment by tristan0x** [comment]
This project doesn't rely on tools or libraries released under viral licenses.Let's get _aligned_ and use Apache licence...

**Pull request merged**
